image: gcc

compile: 
  script:
    - echo "Building started"
    - mkdir build
    - g++ project.cpp -o build/run
    - echo "Building finished"

check_file_exist:
  stage: test
  script:
    - ./build/run
    - exists:
      - "output.txt"